[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = "0.5.0"
spin = "0.9"
x86_64 = "0.15"
linked_list_allocator = "0.10"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
bitflags = "2.4"

[features]
default = []
